events {
    worker_connections 4096;
}

http {
    server {
        listen 80;
        listen [::]:80;
        server_name 192.168.0.120;
        
        root /etc/static/web-site;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}

